// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wphwhvaruknxtvjibkiq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndwaHdodmFydWtueHR2amlia2lxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzU0NjQ0NTIsImV4cCI6MjA5MTA0MDQ1Mn0.oRJaRcExOyi3ruj6st6TdmI1oB5C2bT-ycb53EugvRA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});